### ISSUE TITLE
Authorize endpoint redirects to empty login page

### ISSUE THREAD

**Issue by nolanbrown** [producthunt/producthunt-api#93] opened 2016-04-28 21:45 UTC
When I try to load the authorize endpoint when I'm not logged in, I'm redirected to https://api.producthunt.com/login which renders as an empty page and I'm unable to login from there.

**Comment by andreasklinger** [comment] 2016-04-28 21:48
thanks for pointing out - unfortunately this bug happened in a (by design) test blind area of the flow
i will look into seeing if we can fix it

**Comment by polaski** [comment] 2016-05-07 18:17
+1 here. Basically the API is completely unusable because of this bug. Would appreciate it if you could look into this sooner than later. It's not like we're requesting some random feature or a minor bug, no other discussion really matters if the API itself is not working at all. I know you guys are a startup and have priorities, but I do think this is important unless you don't care at all about the API going forward.

**Comment by vesln** [comment] 2016-05-09 11:51
can you try again and let me know if it's working fine now?

**Comment by andreasklinger** [comment] 2016-05-16 21:12
i discovered another related bug - looking into this again

**Comment by andreasklinger** [comment] 2016-05-17 20:06
Related bugs should be fixed - please retry - will close for now - feel free to reopen if i am wrong

**Closed by andreasklinger** 2016-05-17 20:06 UTC
Labels: bug
